#!/usr/bin/env python3
"""Generate SQL DDL/DML and CSV from administrative-division JSON data.

Reads per-version JSON trees produced by ``tools/fetch_xzqh.py`` and emits a
generic, drop-in dataset for other projects:

  dist/<version>/
    mysql/{schema.sql, data_full.sql, data_upsert.sql}
    postgresql/{schema.sql, data_full.sql, data_upsert.sql}
    csv/region.csv
    README.md

Design:
  - Single self-referencing table ``region`` with a ``version`` column so
    multiple versions can coexist; unique key on (version, code).
  - FK (version, parent_code) -> (version, code) ON DELETE CASCADE links the
    hierarchy and propagates deletions.
  - ``data_full.sql``   = TRUNCATE-equivalent (DELETE WHERE version=...) + INSERT.
  - ``data_upsert.sql`` = idempotent UPSERT on (version, code).
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

DEFAULT_BATCH_SIZE = 500
COLUMNS = ["version", "code", "name", "level", "type", "parent_code", "sort_order"]

LEVEL_NAMES = {1: "省级", 2: "地级", 3: "县级", 4: "乡级"}


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------

def detect_latest_version(data_root: Path) -> str:
    if not data_root.is_dir():
        raise FileNotFoundError(f"data directory not found: {data_root}")
    candidates = [
        p.name for p in data_root.iterdir()
        if p.is_dir() and (p / "province_index.json").exists()
    ]
    if not candidates:
        raise FileNotFoundError(
            f"no version directories with province_index.json under {data_root}"
        )
    return sorted(candidates)[-1]


def load_version(data_root: Path, version: str) -> list[dict[str, Any]]:
    version_dir = data_root / version
    index_path = version_dir / "province_index.json"
    if not index_path.exists():
        raise FileNotFoundError(f"missing province_index.json: {index_path}")
    province_index = json.loads(index_path.read_text(encoding="utf-8"))

    rows: list[dict[str, Any]] = []
    for entry in province_index:
        tree_path = version_dir / entry["file"]
        tree = json.loads(tree_path.read_text(encoding="utf-8"))
        _walk_tree(tree, parent_code=None, sort_order=0, rows=rows)
    return rows


def _walk_tree(
    node: dict[str, Any],
    parent_code: str | None,
    sort_order: int,
    rows: list[dict[str, Any]],
) -> None:
    code = str(node.get("code") or "")
    rows.append({
        "code": code,
        "name": str(node.get("name") or ""),
        "level": int(node.get("level") or 0),
        "type": str(node.get("type") or ""),
        "parent_code": parent_code,
        "sort_order": sort_order,
    })
    children = node.get("children") or []
    for idx, child in enumerate(children):
        _walk_tree(child, parent_code=code or None, sort_order=idx, rows=rows)


def build_stats(rows: list[dict[str, Any]]) -> dict[str, int]:
    stats: dict[str, int] = {"total": len(rows)}
    for lvl in (1, 2, 3, 4):
        stats[f"level_{lvl}"] = sum(1 for r in rows if r["level"] == lvl)
    return stats


# --------------------------------------------------------------------------
# SQL literal helpers
# --------------------------------------------------------------------------

def _sql_escape(value: str) -> str:
    # Standard SQL string literal: double single-quotes; both MySQL (with
    # default sql_mode) and PostgreSQL accept this. Backslashes are kept as-is.
    return value.replace("'", "''")


def _sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return f"'{_sql_escape(str(value))}'"


def _row_values(row: dict[str, Any], version: str) -> str:
    vals = [
        _sql_literal(version),
        _sql_literal(row["code"]),
        _sql_literal(row["name"]),
        str(row["level"]),
        _sql_literal(row["type"]),
        _sql_literal(row["parent_code"]),
        str(row["sort_order"]),
    ]
    return "(" + ", ".join(vals) + ")"


def _sort_for_load(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    # Parents-first so that even FK-strict imports succeed without deferral.
    return sorted(rows, key=lambda r: (r["level"], r["code"]))


# --------------------------------------------------------------------------
# Schema DDL
# --------------------------------------------------------------------------

MYSQL_SCHEMA = """\
-- ============================================================================
-- 行政区划 (Administrative Division) - MySQL / MariaDB Schema
-- 单表自引用 + version 列，支持多版本共存与级联删除
-- Generated by tools/generate_sql.py
-- ============================================================================

DROP TABLE IF EXISTS region;

CREATE TABLE region (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT  COMMENT '自增主键',
  version      VARCHAR(32)     NOT NULL                 COMMENT '数据版本，如 Xzqh20251231',
  code         VARCHAR(12)     NOT NULL                 COMMENT '行政区划代码 (2/4/6/9 位)',
  name         VARCHAR(64)     NOT NULL                 COMMENT '行政区划名称',
  level        TINYINT         NOT NULL                 COMMENT '层级 1省 2地级 3县级 4乡级',
  type         VARCHAR(32)     NOT NULL DEFAULT ''      COMMENT '类型，如 省/直辖市/地级市/市辖区/街道',
  parent_code  VARCHAR(12)     DEFAULT NULL             COMMENT '父级 code，顶层为 NULL',
  sort_order   INT             NOT NULL DEFAULT 0       COMMENT '同级内顺序',
  PRIMARY KEY (id),
  UNIQUE KEY uk_region_version_code (version, code),
  KEY idx_region_version_parent (version, parent_code),
  KEY idx_region_version_level (version, level),
  KEY idx_region_name (name),
  CONSTRAINT fk_region_parent FOREIGN KEY (version, parent_code)
    REFERENCES region (version, code)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='行政区划 - 单表自引用 / 多版本共存';
"""

PG_SCHEMA = """\
-- ============================================================================
-- 行政区划 (Administrative Division) - PostgreSQL Schema
-- 单表自引用 + version 列，支持多版本共存与级联删除
-- Generated by tools/generate_sql.py
-- ============================================================================

DROP TABLE IF EXISTS region CASCADE;

CREATE TABLE region (
  id           BIGSERIAL    PRIMARY KEY,
  version      VARCHAR(32)  NOT NULL,
  code         VARCHAR(12)  NOT NULL,
  name         VARCHAR(64)  NOT NULL,
  level        SMALLINT     NOT NULL,
  type         VARCHAR(32)  NOT NULL DEFAULT '',
  parent_code  VARCHAR(12)  DEFAULT NULL,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  CONSTRAINT uk_region_version_code UNIQUE (version, code),
  CONSTRAINT fk_region_parent FOREIGN KEY (version, parent_code)
    REFERENCES region (version, code)
    ON DELETE CASCADE ON UPDATE CASCADE
    DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_region_version_parent ON region (version, parent_code);
CREATE INDEX idx_region_version_level  ON region (version, level);
CREATE INDEX idx_region_name           ON region (name);

COMMENT ON TABLE  region              IS '行政区划 - 单表自引用 / 多版本共存';
COMMENT ON COLUMN region.version      IS '数据版本，如 Xzqh20251231';
COMMENT ON COLUMN region.code         IS '行政区划代码 (2/4/6/9 位)';
COMMENT ON COLUMN region.name         IS '行政区划名称';
COMMENT ON COLUMN region.level        IS '层级 1省 2地级 3县级 4乡级';
COMMENT ON COLUMN region.type         IS '类型，如 省/直辖市/地级市/市辖区/街道';
COMMENT ON COLUMN region.parent_code  IS '父级 code，顶层为 NULL';
COMMENT ON COLUMN region.sort_order   IS '同级内顺序';
"""


# --------------------------------------------------------------------------
# DML generation
# --------------------------------------------------------------------------

def gen_full_sql(
    rows: list[dict[str, Any]], version: str, dialect: str, batch_size: int
) -> str:
    sorted_rows = _sort_for_load(rows)
    lines: list[str] = [
        f"-- Full load for version={version} ({dialect})",
        "-- Generated by tools/generate_sql.py",
        f"-- Rows: {len(sorted_rows)}",
        f"-- WARNING: deletes existing rows for version='{version}' before inserting.",
        "",
    ]

    if dialect == "mysql":
        lines.append("SET FOREIGN_KEY_CHECKS = 0;")
        lines.append(f"DELETE FROM region WHERE version = '{_sql_escape(version)}';")
    else:
        lines.append("BEGIN;")
        lines.append("SET CONSTRAINTS ALL DEFERRED;")
        lines.append(f"DELETE FROM region WHERE version = '{_sql_escape(version)}';")
    lines.append("")

    insert_prefix = f"INSERT INTO region ({', '.join(COLUMNS)}) VALUES"
    for start in range(0, len(sorted_rows), batch_size):
        chunk = sorted_rows[start:start + batch_size]
        values = ",\n".join("  " + _row_values(r, version) for r in chunk)
        lines.append(insert_prefix)
        lines.append(values + ";")
        lines.append("")

    if dialect == "mysql":
        lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    else:
        lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def gen_upsert_sql(
    rows: list[dict[str, Any]], version: str, dialect: str, batch_size: int
) -> str:
    sorted_rows = _sort_for_load(rows)
    lines: list[str] = [
        f"-- Idempotent UPSERT for version={version} ({dialect})",
        "-- Generated by tools/generate_sql.py",
        f"-- Rows: {len(sorted_rows)}",
        "-- Safe to run multiple times; matches by (version, code).",
        "",
    ]

    if dialect == "mysql":
        lines.append("SET FOREIGN_KEY_CHECKS = 0;")
        suffix = (
            "ON DUPLICATE KEY UPDATE "
            "name = VALUES(name), "
            "level = VALUES(level), "
            "type = VALUES(type), "
            "parent_code = VALUES(parent_code), "
            "sort_order = VALUES(sort_order);"
        )
    else:
        lines.append("BEGIN;")
        lines.append("SET CONSTRAINTS ALL DEFERRED;")
        suffix = (
            "ON CONFLICT (version, code) DO UPDATE SET "
            "name = EXCLUDED.name, "
            "level = EXCLUDED.level, "
            "type = EXCLUDED.type, "
            "parent_code = EXCLUDED.parent_code, "
            "sort_order = EXCLUDED.sort_order;"
        )
    lines.append("")

    insert_prefix = f"INSERT INTO region ({', '.join(COLUMNS)}) VALUES"
    for start in range(0, len(sorted_rows), batch_size):
        chunk = sorted_rows[start:start + batch_size]
        values = ",\n".join("  " + _row_values(r, version) for r in chunk)
        lines.append(insert_prefix)
        lines.append(values)
        lines.append(suffix)
        lines.append("")

    if dialect == "mysql":
        lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    else:
        lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# CSV
# --------------------------------------------------------------------------

def write_csv(path: Path, rows: list[dict[str, Any]], version: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sorted_rows = _sort_for_load(rows)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(COLUMNS)
        for r in sorted_rows:
            writer.writerow([
                version,
                r["code"],
                r["name"],
                r["level"],
                r["type"],
                "" if r["parent_code"] is None else r["parent_code"],
                r["sort_order"],
            ])


# --------------------------------------------------------------------------
# README per version
# --------------------------------------------------------------------------

def gen_readme(version: str, stats: dict[str, int]) -> str:
    return f"""# 行政区划数据 - `{version}`

本目录由 `tools/generate_sql.py` 生成，包含可直接接入其他项目的行政区划资源。

## 数据概览
| 指标 | 数量 |
|------|------|
| 总记录数 | {stats['total']} |
| 省级 (level=1) | {stats['level_1']} |
| 地级 (level=2) | {stats['level_2']} |
| 县级 (level=3) | {stats['level_3']} |
| 乡级 (level=4) | {stats['level_4']} |

## 目录结构
```
{version}/
├── mysql/
│   ├── schema.sql        建表
│   ├── data_full.sql     全量替换（DELETE WHERE version=… 后 INSERT）
│   └── data_upsert.sql   幂等 UPSERT（按 (version, code) 冲突更新）
├── postgresql/
│   ├── schema.sql
│   ├── data_full.sql
│   └── data_upsert.sql
├── csv/
│   └── region.csv
└── README.md
```

## 表结构 `region`
| 列 | 类型 | 说明 |
|----|------|------|
| id | BIGINT | 自增主键 |
| version | VARCHAR(32) | 数据版本（如 `{version}`），支持多版本共存 |
| code | VARCHAR(12) | 行政区划代码 |
| name | VARCHAR(64) | 行政区划名称 |
| level | TINYINT/SMALLINT | 1省 2地级 3县级 4乡级 |
| type | VARCHAR(32) | 省/直辖市/地级市/市辖区/街道 等 |
| parent_code | VARCHAR(12) | 父级代码（顶层为 NULL） |
| sort_order | INT | 同级内顺序 |

约束：
- `UNIQUE (version, code)`
- `FOREIGN KEY (version, parent_code) REFERENCES region(version, code) ON DELETE CASCADE ON UPDATE CASCADE`

## 接入方式

### MySQL / MariaDB
```bash
mysql -uroot -p mydb < mysql/schema.sql
mysql -uroot -p mydb < mysql/data_full.sql     # 或 mysql/data_upsert.sql
```

### PostgreSQL
```bash
psql -d mydb -f postgresql/schema.sql
psql -d mydb -f postgresql/data_full.sql       # 或 postgresql/data_upsert.sql
```

### 通过 CSV 加载（更快）
MySQL：
```sql
LOAD DATA LOCAL INFILE 'csv/region.csv' INTO TABLE region
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\\n' IGNORE 1 LINES
  (version, code, name, level, type, @parent, sort_order)
  SET parent_code = NULLIF(@parent, '');
```

PostgreSQL：
```sql
\\copy region(version, code, name, level, type, parent_code, sort_order)
  FROM 'csv/region.csv' WITH (FORMAT csv, HEADER true, NULL '');
```

## 版本更新
1. 重新运行 `tools/fetch_xzqh.py` 抓取最新版本。
2. 运行 `python tools/generate_sql.py --version <新版本>` 生成对应 `dist/<新版本>/`。
3. 选择导入方式：
   - **替换当前版本**：`data_full.sql` 会先删本版本数据再插入。
   - **幂等同步**：`data_upsert.sql` 可重复执行而不丢历史。
   - **多版本并存**：`version` 列已就绪，应用查询时 `WHERE version = ?` 即可。

## 示例查询

最新版本：
```sql
SELECT MAX(version) FROM region;
```

某省下的地级市：
```sql
SELECT code, name FROM region
WHERE version = '{version}' AND parent_code = '43' AND level = 2
ORDER BY sort_order, code;
```

省 → 市 → 县 三级展开（湖南）：
```sql
SELECT p.name AS province, c.name AS city, d.name AS county
FROM region p
JOIN region c ON c.version = p.version AND c.parent_code = p.code
JOIN region d ON d.version = p.version AND d.parent_code = c.code
WHERE p.version = '{version}' AND p.code = '43'
ORDER BY c.code, d.code;
```

向上回溯（已知乡镇代码反查省/市/县/乡）：
```sql
WITH RECURSIVE chain AS (
  SELECT * FROM region WHERE version = '{version}' AND code = '430102001'
  UNION ALL
  SELECT r.* FROM region r
    JOIN chain c ON r.version = c.version AND r.code = c.parent_code
)
SELECT level, code, name FROM chain ORDER BY level;
```

> 数据源：中华人民共和国民政部 <https://dmfw.mca.gov.cn/XzqhVersionPublish.html>
"""


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate SQL & CSV from administrative-division JSON data.",
    )
    parser.add_argument("--data-dir", default="data",
                        help="root of versioned JSON data, default: data")
    parser.add_argument("--version",
                        help="version directory name; default: latest under data-dir")
    parser.add_argument("--output-dir", default="dist",
                        help="output root, default: dist")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE,
                        help=f"rows per INSERT statement, default: {DEFAULT_BATCH_SIZE}")
    parser.add_argument("--dialect", action="append", choices=["mysql", "postgresql"],
                        help="emit dialect (repeatable); default: both")
    parser.add_argument("--no-csv", action="store_true",
                        help="skip CSV output")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data_root = Path(args.data_dir)
    version = args.version or detect_latest_version(data_root)
    dialects = args.dialect or ["mysql", "postgresql"]

    print(f"version    : {version}")
    print(f"dialects   : {', '.join(dialects)}")
    print("loading rows...")
    rows = load_version(data_root, version)
    stats = build_stats(rows)
    print(f"loaded     : {stats['total']} rows  "
          f"(L1={stats['level_1']}, L2={stats['level_2']}, "
          f"L3={stats['level_3']}, L4={stats['level_4']})")

    out_dir = Path(args.output_dir) / version
    out_dir.mkdir(parents=True, exist_ok=True)

    for dialect in dialects:
        dialect_dir = out_dir / dialect
        dialect_dir.mkdir(parents=True, exist_ok=True)
        schema = MYSQL_SCHEMA if dialect == "mysql" else PG_SCHEMA
        (dialect_dir / "schema.sql").write_text(schema, encoding="utf-8")
        (dialect_dir / "data_full.sql").write_text(
            gen_full_sql(rows, version, dialect, args.batch_size), encoding="utf-8")
        (dialect_dir / "data_upsert.sql").write_text(
            gen_upsert_sql(rows, version, dialect, args.batch_size), encoding="utf-8")
        print(f"  wrote {dialect_dir}/")

    if not args.no_csv:
        write_csv(out_dir / "csv" / "region.csv", rows, version)
        print(f"  wrote {out_dir / 'csv' / 'region.csv'}")

    (out_dir / "README.md").write_text(gen_readme(version, stats), encoding="utf-8")
    print(f"  wrote {out_dir / 'README.md'}")
    print(f"done -> {out_dir}")


if __name__ == "__main__":
    main()
